theme: jekyll-theme-minimal
title: Francisco Salces Carcoba
logo: media/pacoandrbchip
description: Quantum physicist of sorts
defaults:
  - scope:
      path: "docs"
      path: "media"
    values:
      image: true
