theme: jekyll-theme-minimal
title: Francisco Salces Carcoba
logo: /media/pacoandrbchip.png
description: Quantum physicist of sorts
defaults:
  - scope:
      path: "docs"
      path: "media"
    values:
      image: true
